manifest = "99a3d39417ede4cb925d7dd93d357ae02e21c688634477a6f631b9a43b6576a7"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "f2f2d0d85496b72eeff1186518deb7e23c757bfd"
