manifest = "fdf5853324be64ea310a653a11581af8842c4ba63ceb6361640db8bc5a89a66d"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.24.0" ]
revision = "37278170bcbe6e22f6eebed0d33d5df4e0d015e1"
