manifest = "6fafa5e70fd96782aef707dd326746ab1f3bea5ee7659fe2a38f63cf39418b5c"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.63.0" ]
revision = "f4f11472a3df6451547ae5c1023434485590e80e"
